### ISSUE TITLE
__Secure-next-auth.session-token

### ISSUE THREAD

**Issue by Zubinexu** [consensual-hallucination/midjourney-dl#1]
cannot find this anywhere

**Comment by pablo-01** [comment]
Firefox example:
![image](https://github.com/consensual-hallucination/midjourney-dl/assets/35709452/bcb28701-21ed-453a-bb34-7a1f3304c677)

**Comment by consensual-hallucination** [comment]
Firefox example:
![image](https://github.com/consensual-hallucination/midjourney-dl/assets/83740044/2add53cd-9b7e-461a-b4d2-c2e769aeaea7)

**Comment by Zubinexu** [comment]
thanks
