### ISSUE TITLE
upscale image limits

### ISSUE THREAD

**Issue by nevertoday** [consensual-hallucination/midjourney-dl#3]
I am writing to inquire about a problem that I have been experiencing with your plugin.

When using the program to download images, I have noticed that only the ones that have been previously clicked on and enlarged are able to be downloaded. The regular-sized images cannot be downloaded through the program.

Could you please explain why this is happening? Is there a setting or option that needs to be adjusted in order for all images, regardless of size, to be downloadable?

**Comment by consensual-hallucination** [comment]
This script is set to only download upscaled images.
![image](https://github.com/consensual-hallucination/midjourney-dl/assets/83740044/aae1ab11-e8ae-4516-8852-d914860062f9)

It should be easy enough to modify the code to also download the 'quad' images. I don't have access to Midjourney anymore so I'm unable to add this option.

**Comment by nevertoday** [comment]
omg . I have 17000 unupsacle image need to downlod ....
