### ISSUE TITLE
__Secure-next-auth.session-token doesn't work anymore..

### ISSUE THREAD

**Issue by nicolai256** [consensual-hallucination/midjourney-dl#4]
it seems like __Secure-next-auth.session-token doesn't work anymore because the token gets refreshed every second?

**Comment by jcollier7** [comment]
No longer working for me either.
...raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)...

**Comment by consensual-hallucination** [comment]
I was going to fix this but I no longer have paid account so I'm unable to test.
